### PR TITLE
Add host prop to <vue3-youtube>

### PR DESCRIPTION
**Pull request by Coder-Iro**

### CODE REVIEW

**Comment by NomNes** [comment]
What is the motivation to change the package manager specifically in this package? If there is a good reason for this, I would discuss. But I suggest putting it in a separate PR

**Comment by Coder-Iro** [comment]
If you want to, I will seperate yarn berry to another PR

**Comment by NomNes** [comment]
Yes, that would be great! As soon as I find the time, I'll see what's new in yarn)
Thank you for your PR!

**Comment by Coder-Iro** [comment]
I reverted the commit related to yarn berry.

**Comment by Coder-Iro** [comment]
When this change will be released?

**Comment by NomNes** [comment]
already

**Pull request merged**
